Add labels to all commands
chris-sanders/oh-my-replicated pull request #1
Opened 2021-11-15 19:22 UTC by emosbaugh

2021-11-18 18:15 UTC, chris-sanders requested changes
One particular comment what are your thoughts on that?

2021-11-18 18:15 UTC, chris-sanders commented on replicated-gcommands/replicated-gcommands.plugin.zsh
> +    instance_name_prefix="${GUSER}-$1"
Using tags why are you inserting a hard coded prefix that users can't change? A user can get this same effect by simply setting a prefix so I tend to think the scripts shouldn't force it.

2021-11-18 18:15 UTC, chris-sanders commented on replicated-gcommands/replicated-gcommands.plugin.zsh
> +    local instance_name_prefix="${GUSER}-${instance}"
As above

2021-11-18 18:15 UTC, chris-sanders commented on replicated-gcommands/replicated-gcommands.plugin.zsh
> +  local instance_name_prefix="${GUSER}-$1"
as above

2021-11-18 18:15 UTC, chris-sanders commented on replicated-gcommands/replicated-gcommands.plugin.zsh
> +  local instance_name_prefix="${GUSER}-$1"
as above I won't repeat it 3x times

2021-11-18 18:15 UTC, chris-sanders commented on replicated-gcommands/replicated-gcommands.plugin.zsh
> +  local device_name_prefix="${GUSER}-$1-disk-$2"
I do think adding a prefix on the disks is fine, you can't (I don't think) label a disk and you don't really see the disk names either.

2021-11-18 18:17 UTC, emosbaugh commented on replicated-gcommands/replicated-gcommands.plugin.zsh
> +    instance_name_prefix="${GUSER}-$1"
Makes sense. I'll update as a separate var.

2021-11-30 14:27 UTC, emosbaugh commented
I've made GPREFIX a separate variable for adding a prefix to the name rather than repurposing GUSER.

2021-11-30 14:49 UTC, merged